# k8s/ingress-demo.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: netflix-alb-k8s-61161915.eu-west-1.elb.amazonaws.com
    http:
      paths:
        - path: /status
          pathType: Exact
          backend:
            service:
              name: netflix-catalog-service
              port:
                number: 8080
        - path: /
          pathType: Prefix
          backend:
            service:
              name: netflix-service
              port:
                number: 3000
